# Generated by Django 5.1 on 2024-08-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_followed_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followed_user',
            new_name='following',
        ),
    ]
